### PR TITLE
#157773975 Adds User signin and sign up pages

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Adds navigation to the web app's user sign in and sign up pages.

* Changes the color scheme of the app

* Add an ico-icon

#### Description of Task to be completed?
A user should be able to navigate to the web app's homepage, and from there, the user sign-in or sign up page.

#### How to test the App manually
On a web browser:

* Download the [Zip from GitHub](https://github.com/artorious/MaintenanceTracker/archive/ft-user-signin-and-signout-157773975.zip)

* Extract the MaintenanceTracker folder.

* In the IU folder,  open  `index.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone  https://github.com/artorious/MaintenanceTracker.git`

* Run `git checkout ft-user-signin-and-signout-157773975`

* Open  `MantenanceTracker/UI/index.html` on a browser

* Navigate to admin sign in by clicking `User` on the navigation bar or `Sign Up` button

#### Any background context you want to provide?
The Website UI is to be developed in HTML5 & CSS3 

#### What are the relevant pivotal tracker stories?
[#157773975](https://www.pivotaltracker.com/story/show/157773975)

#### Screenshots 

user_signin
user_signup_screenshot

### CODE REVIEW

**Comment by maxwellgithinji** [comment]
Nice Pull request, however, before the paragraph "On web Browser" Input the heading "**How this should be manually tested**"
Also, You should have started your project with your project with a develop branch off your master branch. Never push directly to the master branch.
checkout this git convention link: https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices

**Comment by PaulKitonyi** [comment]
@artorious consider @maxwellgithinji feedback.Its all i could say.

**Comment by joelmachango** [comment]
@maxwellgithinji Has raised some good points. I would recommend you add a nice background color/ image. Consider this resource for styling with CSS that I've been using:

https://www.w3schools.com/css/

Your PR is well structured

**Comment by artorious** [comment]
Hi @maxwellgithinji Thanks for the PR catch. Will also pay attention to merges. Thanks

**Comment by artorious** [comment]
Hi, @joelmachango I have a few ideas bubbling. Ultimately, I'm going for an extremely clean UI. More Styling ahead

**Pull request merged**
