### PR TITLE
#157774457 Build out web app's homepage

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?
Adds navigation to the web app's homepage

#### Description of Task to be completed?
A user should be able to navigate to the web app's homepage

#### How should this be manually tested?
On Webbrowser:
* Download the [Zip from GitHub](https://github.com/artorious/MaintenanceTracker/archive/ft-UI-homepage-%23157774457.zip)
* Extract the MaintenanceTracker folder.
* In the IU folder,  open  `index.html` on a browser

On a  terminal (Linux):
* Install and set up git `sudo apt install git`
* Clone the repository `git clone https://github.com/artorious/MaintenanceTracker.git`
* Open  `MantenanceTracker/UI/index.html` on a browser

#### Any background context you want to provide?
The Website UI is to be developed in HTML5 & CSS3 

#### What are the relevant pivotal tracker stories?
[#157774457](https://www.pivotaltracker.com/story/show/157774457)

##### Screenshot
homepage_screenshot

### CODE REVIEW

**Comment by lawrenceChege** [comment]
Good commits and well-structured PR.
maybe next time include the screenshot on the PR

**Comment by Slinjez** [comment]
Looks okey to me

**Comment by johnmusiu** [comment]
- PR well structured.
- You have one of the most elaborate 'how should this be manually tested?" sections.

**Comment by Slinjez** [comment]
@johnmusiu indeed, this is the nest explained testing section.

**Pull request merged**
